<?xml version="1.0"?>
<package format="3"> 
  <name>mvp_c2_traffic_manager</name>
  <version>0.0.0</version>
  <description>The communication package</description>

  <maintainer email="jason_miller@uri.edu">Jason Miller</maintainer>
  <author email="jason_miller@uri.edu">Jason Miller</author>

  <license>GPLv3</license>

  <buildtool_depend>ament_cmake</buildtool_depend>  

  <build_depend>rclcpp</build_depend> 
  
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>proto</depend>
  <depend>goby</depend>
  <depend>yaml-cpp</depend>
  <depend>ament_index_cpp</depend>
  <depend>dccl</depend>

  <member_of_group>rosidl_interface_packages</member_of_group>


  <export>
  <build_type>ament_cmake</build_type>
  </export>
</package>
