tdma:
  default: &tdma
    source: 1
    destination: 2
    slot_time: 5
    max_frame_bytes: 32
    max_num_frames: 1
    rate: 0

  acomms:
    slots: 
      - <<: *tdma
        source: 1
        destination: 2
        slot_time: 10

      - <<: *tdma
        source: 2
        destination: 1
        max_frame_bytes: 256
        slot_time: 30