reporter/mvp_c2_traffic_control:
  ros__parameters:

    max_frame_size: 50

    # --- Buffer Global Settings ---
    dynamic_buffer:
      max_total_size: 150
      dccl_intake_message_list: ["Odometry", "GeoPose", "PowerMonitor", ReportRosLaunch]

    # --- Message Specific Rules ---
    message_rules:
      Odometry:
        priority: 10
        ttl_seconds: 5
      GeoPose:
        priority: 12
        ttl_seconds: 300
      PowerMonitor:
        priority: 5
        ttl_seconds: 10
      ReportRosLaunch:
        priority: 20
        ttl_seconds: 100
